version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: /backend-app/Dockerfile-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend-app:/database
    environment:
      DATABASE_URL: postgresql://postgres:Plotar1404@db:5432/circular
      MINIO_URL: "http://minio:9000"
    networks:
      - app-network

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: "Root123"
      MINIO_ROOT_PASSWORD: "Root123312213n"
    command: server --console-address :9001 /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ~/minio/data:/data
    networks:
      - app-network  # Заменено на app-network

  frontend:
    build:
      context: .
      dockerfile: /frontend-app/Dockerfile-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-app:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Plotar1404
      POSTGRES_DB: circular
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
